project:
  type: book

book:
  title: "Cytopia Proceedings"
  author: "CiuP"
  date: "7/6/2026"
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - part: gene_tonic.qmd
      chapters: 
        - _sub/cytopia/cycles/2026/bio/conferences/bio-1/topics/learning_gliding_mammals/index.qmd
        - _sub/cytopia/cycles/2026/bio/conferences/bio-1/topics/immune_tolerance/index.qmd
        - _sub/cytopia/cycles/2026/bio/conferences/bio-1/topics/microbiome/index.qmd
    - part: diplocite.qmd
      chapters: 
        - _sub/cytopia/cycles/2026/diplo/conferences/diplo-1/topics/tierra_and_territorio/index.qmd
        - _sub/cytopia/cycles/2026/diplo/conferences/diplo-1/topics/ilo/index.qmd
        - _sub/cytopia/cycles/2026/diplo/conferences/diplo-1/topics/complex_global_landscape/index.qmd
    - part: technology.qmd
      chapters: 
        - _sub/cytopia/cycles/2026/tech/conferences/tech_1/topics/user_sovereignty/index.qmd
        - _sub/cytopia/cycles/2026/tech/conferences/tech_1/topics/re-identification/index.qmd
        - _sub/cytopia/cycles/2026/tech/conferences/tech_1/topics/sudoku_kills_modern_ai/index.qmd
        - _sub/cytopia/cycles/2026/tech/conferences/tech_1/topics/ai_safety/index.qmd
        - _sub/cytopia/cycles/2026/tech/conferences/tech_2/topics/autobiography/index.qmd
        - _sub/cytopia/cycles/2026/tech/conferences/tech_2/topics/environment/index.qmd
        - _sub/cytopia/cycles/2026/tech/conferences/tech_2/topics/ocean/index.qmd
        - _sub/cytopia/cycles/2026/tech/conferences/tech_3/topics/museology/index.qmd
        - _sub/cytopia/cycles/2026/tech/conferences/tech_3/topics/cinema/index.qmd
        - _sub/cytopia/cycles/2026/tech/conferences/tech_3/topics/philosophy/index.qmd
    - references.qmd
  appendices:
    - authors.qmd

bibliography: _sub/cytopia/bib/ref.bib

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    fig-pos: '!htb'
    title-block-style: none
    documentclass: scrbook
    classoption: ["titlepage=false"]
    papersize: a5
    toc: true
    toc-depth: 1
    include-in-header:
      text: |
        \usepackage{fontawesome6}
        \usepackage{qrcode}
        \usepackage{pdfpages}

        \renewcommand{\labelitemi}{--}

        \newcommand{\marginqrcode}[3]{%
          \setlength{\marginparwidth}{15mm}%
          \setlength{\marginparsep}{0mm}%
          \marginpar{%
              \centering
              \raisebox{#1}{%
                  \begin{minipage}{12mm}
                      \centering
                      \qrcode[level=L,height=12mm]{#2}

                      \vspace{0.1cm}
                      \tiny
                      #3
                  \end{minipage}%
              }%
          }%
        }

        \newcommand{\marginqrcodeprofile}[1]{\marginqrcode{0mm}{#1}{\faUser}}
    include-after-body: fig/after-body.tex
    template-partials:
      - fig/before-body.tex
      - fig/title.tex
    geometry:
      - inner=15mm
      - outer=15mm
      - top=15mm
      - bottom=25mm
      - bindingoffset=0mm


language:
  section-title-chapters: "Module"